"""
Django settings for supplychain project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys

# On Windows, default console encoding (cp1252) can't encode Unicode (e.g. → in logs).
# Avoid UnicodeEncodeError when libraries log messages containing such characters.
if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

# Load .env from project root so os.getenv() sees TAVILY_API_KEY, etc.
from dotenv import load_dotenv
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Fix "by_alias: NoneType cannot be converted to PyBool" on some machines (e.g. different
# Pydantic/OS builds). Ensures by_alias is never None when passed to model_dump.
try:
    import pydantic
    _model_dump_orig = pydantic.BaseModel.model_dump

    def _model_dump_patch(self, *args, by_alias=None, **kwargs):
        if by_alias is None:
            by_alias = False
        return _model_dump_orig(self, *args, by_alias=by_alias, **kwargs)

    pydantic.BaseModel.model_dump = _model_dump_patch
except Exception:
    pass  # don't break startup if pydantic structure changes

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pqy8me9p!6gwoxuo0ofshbwzoou60run_-7)szolstvdoog492'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'manufacturer',
    'supplier',
    'home',
    'negotiation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'supplychain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # For global templates
            os.path.join(BASE_DIR, 'home/templates'),  # For home app templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'supplychain.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # Using Path object with /
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Global static files
    os.path.join(BASE_DIR, 'manufacturer/static'),  # Manufacturer static files
    os.path.join(BASE_DIR, 'supplier/static'),  # Supplier static files
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
AUTHENTICATION_BACKENDS = [
    'manufacturer.backends.ManufacturerBackend',
    'supplier.backends.SupplierBackend',
    'django.contrib.auth.backends.ModelBackend',  # fallback
]

LOGIN_URL = 'home'
LOGIN_REDIRECT_URL = 'home'  # Added for better redirect after login
LOGOUT_REDIRECT_URL = 'home'  # Added for better redirect after logout

# supplychain/settings.py

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # e.g., smtp.gmail.com
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER='machinelearning.mnnlr.siddharth@gmail.com'
EMAIL_HOST_PASSWORD='fmwj hgvv ghlf nnnc'
DEFAULT_FROM_EMAIL = 'machinelearning.mnnlr.siddharth@gmail.com'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



OPENROUTE_API_KEY = "5b3ce3597851110001cf62489fb869a41b884c29a4f0adb4581c6209"